#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
from snakemake.exceptions import WorkflowError
import os
import pandas as pd

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/remote_download.smk"
include: "rules/untar_tcga_genome.smk"
include: "rules/get_fastq_files.smk"
include: "rules/restriction_fragments.smk"
include: "rules/bowtie_index.smk"
include: "rules/render_hicpro_config.smk"
include: "rules/hic_pro.smk"

# Needs to be updated
rule all:
    input:
        expand("results/{dataset}/{dataset}_hicpro_complete.txt", dataset="hic_tissue_PRJNA703392")

