#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
from snakemake.exceptions import WorkflowError
import os
import pandas as pd

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/remote_download.smk"
include: "rules/untar_tcga_genome.smk"
include: "rules/get_fastq_files.smk"
include: "rules/restriction_fragments.smk"
include: "rules/bowtie_index.smk"
include: "rules/render_hicpro_config.smk"
include: "rules/install_hicpro.smk"
include: "rules/hicpro_align.smk"
include: "rules/hicpro_pairs.smk"
#include: "rules/hic_pro.smk"
#include: "rules/merged_hic_pro.smk"

rule all:
    input:
        expand("results/hicpro_pairs/{samp}/hic_results/data/{samp}", samp=samples.index.to_list())

