# this file contains everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples file that contains
# one row per sample that can easily be parsed via pandas.
sra_runtable:
    filename: "config/SraRunTable.csv"
    runid: "Run"
    sampid: "GEO_Accession (exp)"
    layout: "LibraryLayout"

# Samples metadata file
samples_metadata:
    filename: "config/hic_samples_metadata.csv"
    sampid_meta: "geo_accession"

# directory for temps
tmpdir: "/tmp"

# remote downloads
downloads:
    GRCh38.d1.vd1.fa.tar.gz:
        url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
        md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
    v3.1.0.tar.gz:
        url: "https://github.com/nservant/HiC-Pro/archive/refs/tags/v3.1.0.tar.gz"
        md5: "7f1bfbc3ddc708a0b902beebf8a013df"

# download tcga reference genome
download_tcga_genome:
    args: "--remote-name --remote-header-name --output-dir $(dirname {output})"

# decompressing
software:
    hicpro_targz: "resources/downloads/v3.1.0.tar.gz"
    hicpro_dir: "resources/software/hicpro"
    hicpro_bin: "resources/software/hicpro/bin/HiC-Pro"

# sequences 
sequences:
    genome_tcga: "resources/downloads/GRCh38.d1.vd1.fa.tar.gz"
    genome_fa: "resources/genome/GRCh38.d1.vd1.fa"
    genome_fasta: "resources/genome/GRCh38.fasta"

# alignment
bowtie_alignment:
    index_dir: "resources/indexes/bowtie"
    index: "resources/indexes/bowtie/GRCh38"
 
# genome digestion
restriction_fragments: # I should add a dataset thing here
    bed: "resources/restriction_fragments/GRCh38_arima.bed"
    enzyme: "^GATC G^ANTC"  # digest_genome.py works for a list of sites, space separated
    name: "arima"

# fastq files
sra_to_fastq_threads: 8

# hicpro
hicpro:
    hic_tissue_PRJNA703392:
        threads: 48
        sort_mem: "1000M"
        bwt2_index: "resources/indexes/bowtie"
        chr_sizes: "resources/hg38.chrom.sizes"
        ref: "GRCh38"
        genome_frags: "resources/restriction_fragments/GRCh38_arima.bed"
        ligation_site: "GATCGATC,GANTGATC,GANTANTC,GATCANTC"
        resolutions: "1000 5000 10000 20000 40000 150000 500000 1000000"

        
        
